id: I8C43C8BD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:09:18+00:00'
last_modified: '2022-06-08T17:20:38.472741+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15962
  title: སུམ་རྟགས་ཀྱི་རྩ་འགྲེལ་ལ་དཔྱད་པའི་གཏམ་བརྡ་སྤྲོད་པའི་གྲུབ་མཐའི་གླེང་བརྗོད་ཆེན་མོ་འཛམ་གླིང་རྒྱན་གཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    598D:
      image_group_id: I1KG15964
      title: ''
      total_pages: 372
      order: 1
      base_file: 598D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
