id: opecha:P010762
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15962
  title: སུམ་རྟགས་ཀྱི་རྩ་འགྲེལ་ལ་དཔྱད་པའི་གཏམ་བརྡ་སྤྲོད་པའི་གྲུབ་མཐའི་གླེང་བརྗོད་ཆེན་མོ་འཛམ་གླིང་རྒྱན་གཅིག
  volume: ''
  author: ''
