id: P010762
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:23:21.622880
source_metadata:
  id: bdr:W1KG15962
  title: སུམ་རྟགས་ཀྱི་རྩ་འགྲེལ་ལ་དཔྱད་པའི་གཏམ་བརྡ་སྤྲོད་པའི་གྲུབ་མཐའི་གླེང་བརྗོད་ཆེན་མོ་འཛམ་གླིང་རྒྱན་གཅིག
  author: ''
  volumes:
    46a4081743584f7b92460875a977a5a7:
      image_group_id: I1KG15964
      title: ''
      volume_number: 1
      total_pages: 372
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
