id: P010762
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15962
  title: སུམ་རྟགས་ཀྱི་རྩ་འགྲེལ་ལ་དཔྱད་པའི་གཏམ་བརྡ་སྤྲོད་པའི་གྲུབ་མཐའི་གླེང་བརྗོད་ཆེན་མོ་འཛམ་གླིང་རྒྱན་གཅིག
  author: ''
  volumes:
    46a4081743584f7b92460875a977a5a7:
      image_group_id: I1KG15964
      title: ''
      volume_number: 1
      total_pages: 372
      base_file: v001.txt
